# Generated by Django 3.1 on 2020-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200814_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='auctionListing',
            new_name='auction_listing',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='highestBid',
            new_name='bid_amount',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_path',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
