# Generated by Django 3.1 on 2020-08-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listing_category',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_path',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
