# Generated by Django 3.1 on 2020-08-22 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200821_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
