# Generated by Django 3.1 on 2020-08-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_highest_bid',
            field=models.BooleanField(null=True),
        ),
    ]
