# Generated by Django 3.1 on 2020-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_is_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
